allow running the script after each commit when editing history

diff --git a/git/edit-history b/git/edit-history
--- a/git/edit-history
+++ b/git/edit-history
@@ -3,7 +3,44 @@
 # Edit the recent commit history of this GIT repository
 # If no number of commits to edit is specified, it will be defaulted to 5
 
-commits=${1-5}
+usage_and_exit() {
+    echo "Usage: $0 [--safe] [number-of-commits]"
+    echo "    Edit the recent commit history of this GIT repository"
+    echo "    --safe: (optional) run a full build after applying each commit"
+    echo "    number-of-commits: (optional) number of commits to go back when editing history (defaults to 5)"
+    exit 1
+}
 
-git rebase -i HEAD~${commits}
+case $# in
+    0)
+        commits=5
+        ;;
+
+    1)
+        if [[ "$1" = "--safe" ]]; then
+            commits=5
+            options="--exec \"run-full-build\""
+        else
+            commits=$1
+        fi
+        ;;
+    2)
+        if [[ $1 == "--safe" ]]; then
+            commits=$2
+            options="--exec \"run-full-build\""
+        else
+            usage_and_exit
+        fi
+        ;;
+
+    *)
+        usage_and_exit
+        ;;
+esac
+
+# Ensure that the number of commits is actually a positive number
+# Note: using the numeric comparator (-eq) on non-numbers fails, so "$x -eq $x" is works to verify whether $x is a number
+[[ "${commits}" -eq "${commits}" && "${commits}" -gt "0" ]] 2>/dev/null || usage_and_exit
+
+git rebase -i ${options} HEAD~${commits}
 
